version: '3.11'

services:
  homepage_service:
    build: ./homepage_service
    ports:
      - "8001:80"
    depends_on:
      - mongo
  database_service:
    build: ./database_service
    ports:
      - "8002:80"
    depends_on:
      - mongo
  auth_service:
    build: ./auth_service
    ports:
      - "8003:80"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: