---
server:
  http_listen_port: 3100
querier:
  max_concurrent: 2048
  query_scheduler:
  max_outstanding_requests_per_tenant: 4096
  engine:
    timeout: 15m
  query_timeout: 15m
query_range:
  split_queries_by_interval: 0
  parallelise_shardable_queries: false
memberlist:
  join_members:
    - loki:7946
schema_config:
  configs:
    - from: 2021-08-01
      store: tsdb
      object_store: s3
      schema: v12
      index:
        prefix: index_
        period: 24h
common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: minio:9000 
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: supersecret
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist
ruler:
  storage:
    s3:
      bucketnames: loki-ruler