receivers:
  loki:
    protocols:
      http:
    use_incoming_timestamp: true
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4137"
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otelcollector'
          scrape_interval: 15s
          static_configs:
            - targets: ['auth_service:80']

processors:
  attributes:
    actions:
    - action: upsert
      key: loki.attribute.labels
      value: container, job
      
exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  # prometheus:
  #   endpoint: "0.0.0.0:9464"
  #   namespace: fastapi
  file:
    path: ./logtest.json

service:
  pipelines:
    logs:
      receivers: [loki]
      processors: [attributes]
      exporters: [loki]
    metrics:
      receivers: [otlp, prometheus]
      exporters: [file]