receivers:
  loki:
    protocols:
      http:
        endpoint: 0.0.0.0:3500  # Listen on port 3500 for incoming logs over HTTP

    use_incoming_timestamp: true


processors:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        from_attribute: job  # Extract 'job' label added by Promtail
      - action: insert
        key: loki.format
        value: raw

    
exporters:
  loki:
    endpoint: http://gateway:3100/loki/api/v1/push
    headers:
      X-Scope-OrgID: "Main Org."

service:
  pipelines:
    logs:
      receivers: [loki]
      processors: [attributes]
      exporters: [loki]



      