receivers:
  loki:
    protocols:
      http:
    use_incoming_timestamp: true
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otelcol'
          scrape_interval: 15s
          static_configs:
            - targets: ['auth_service:80']

processors:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: container,job
      - action: insert
        key: loki.format
        value: raw
exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  prometheus:
    endpoint: "0.0.0.0:9464"
    namespace: "test-space"
  file:
    path: ./logtest.json

service:
  pipelines:
    logs:
      receivers: [loki]
      processors: [attributes]
      exporters: [loki]
    metrics:
      receivers: [otlp, prometheus]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [file]