global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ['otelcol:9464']
  - job_name: "fastapi"
    static_configs:
      - targets: ['auth_service:80']
